import os
import sys
sys.path.insert(0, os.path.abspath('../../src'))

project   = 'sc-nsforest-qc-nf'
copyright = '2026, NIH-NLM'
author    = 'NIH-NLM'
release   = '1.0.0'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinx.ext.autosummary',
    'myst_parser',
]

# ---------------------------------------------------------------------------
# Nextflow module docs — auto-generated by docs/parse_nf_docs.py
#
# The generated files in docs/source/nextflow/ are committed so that
# ReadTheDocs and GitHub Pages can build without running the script.
# Regenerate locally after any .nf change:
#
#   python3 docs/parse_nf_docs.py
#   make html
# ---------------------------------------------------------------------------

# Accepted source suffixes — .rst and .md (via myst_parser)
source_suffix = {
    '.rst': 'restructuredtext',
    '.md':  'markdown',
}

# Mock imports for packages not available during doc build
autodoc_mock_imports = [
    'numpy',
    'pandas',
    'scanpy',
    'sklearn',
    'scipy',
    'plotly',
    'kaleido',
    'typer',
    'mygene',
    'anndata',
]

autodoc_default_options = {
    'members':         True,
    'member-order':    'bysource',
    'undoc-members':   True,
    'exclude-members': '__weakref__',
}

# Napoleon (Google / NumPy docstring support)
napoleon_google_docstring = True
napoleon_numpy_docstring  = True
napoleon_use_param        = True
napoleon_use_rtype        = True

templates_path   = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

html_theme      = 'sphinx_rtd_theme'
html_static_path = ['_static']
